// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecruitmentService.DatabaseUtils;

#nullable disable

namespace RecruitmentService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260112201731_addrule")]
    partial class addrule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewVolunteer", b =>
                {
                    b.Property<int>("InterviewId")
                        .HasColumnType("integer");

                    b.Property<int>("InterviewersId")
                        .HasColumnType("integer");

                    b.HasKey("InterviewId", "InterviewersId");

                    b.HasIndex("InterviewersId");

                    b.ToTable("InterviewVolunteer");
                });

            modelBuilder.Entity("LocationRecruitmentCampaign", b =>
                {
                    b.Property<int>("LocationsId")
                        .HasColumnType("integer");

                    b.Property<int>("RecruitmentCampaignId")
                        .HasColumnType("integer");

                    b.HasKey("LocationsId", "RecruitmentCampaignId");

                    b.HasIndex("RecruitmentCampaignId");

                    b.ToTable("LocationRecruitmentCampaign");
                });

            modelBuilder.Entity("RecruitmentCampaignVolunteer", b =>
                {
                    b.Property<int>("RecruitmentCampaignId")
                        .HasColumnType("integer");

                    b.Property<int>("VolunteersId")
                        .HasColumnType("integer");

                    b.HasKey("RecruitmentCampaignId", "VolunteersId");

                    b.HasIndex("VolunteersId");

                    b.ToTable("RecruitmentCampaignVolunteer");
                });

            modelBuilder.Entity("VolunteerManagement.Model.BlockedPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("RecruitmentCampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentCampaignId");

                    b.ToTable("BlockedPeriods");
                });

            modelBuilder.Entity("VolunteerManagement.Model.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("AnswersToForm")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecruitingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("RecruitmentCampaignId")
                        .HasColumnType("integer");

                    b.Property<int>("SchedulerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInfoId");

                    b.HasIndex("RecruitmentCampaignId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("VolunteerManagement.Model.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Answers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "LocationId", "DateTime")
                        .IsUnique();

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("VolunteerManagement.Model.InterviewTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Questions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("InterviewTemplates");
                });

            modelBuilder.Entity("VolunteerManagement.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("VolunteerManagement.Model.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<int>("Diet")
                        .HasColumnType("integer");

                    b.Property<string>("FacebookProfile")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("InstagramProfile")
                        .HasColumnType("text");

                    b.Property<int>("ShirtSize")
                        .HasColumnType("integer");

                    b.Property<int>("StudyLanguage")
                        .HasColumnType("integer");

                    b.Property<int>("StudyType")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfo");
                });

            modelBuilder.Entity("VolunteerManagement.Model.RecruitmentCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("InterviewTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecruitmentFormTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RecruitmentCampaigns");
                });

            modelBuilder.Entity("VolunteerManagement.Model.RecruitmentFormTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Questions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentFormTemplates");
                });

            modelBuilder.Entity("VolunteerManagement.Model.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VolunteerStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInfoId");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("VolunteerManagement.Model.VolunteerDisponibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VolunteerDisponibilities");
                });

            modelBuilder.Entity("InterviewVolunteer", b =>
                {
                    b.HasOne("VolunteerManagement.Model.Interview", null)
                        .WithMany()
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerManagement.Model.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("InterviewersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocationRecruitmentCampaign", b =>
                {
                    b.HasOne("VolunteerManagement.Model.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerManagement.Model.RecruitmentCampaign", null)
                        .WithMany()
                        .HasForeignKey("RecruitmentCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecruitmentCampaignVolunteer", b =>
                {
                    b.HasOne("VolunteerManagement.Model.RecruitmentCampaign", null)
                        .WithMany()
                        .HasForeignKey("RecruitmentCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerManagement.Model.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerManagement.Model.BlockedPeriod", b =>
                {
                    b.HasOne("VolunteerManagement.Model.RecruitmentCampaign", null)
                        .WithMany("BlockedPeriods")
                        .HasForeignKey("RecruitmentCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerManagement.Model.Candidate", b =>
                {
                    b.HasOne("VolunteerManagement.Model.PersonalInfo", "PersonalInfo")
                        .WithMany()
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerManagement.Model.RecruitmentCampaign", null)
                        .WithMany("Candidates")
                        .HasForeignKey("RecruitmentCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalInfo");
                });

            modelBuilder.Entity("VolunteerManagement.Model.Volunteer", b =>
                {
                    b.HasOne("VolunteerManagement.Model.PersonalInfo", "PersonalInfo")
                        .WithMany()
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalInfo");
                });

            modelBuilder.Entity("VolunteerManagement.Model.RecruitmentCampaign", b =>
                {
                    b.Navigation("BlockedPeriods");

                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
